defaults:
  - /agent/blendrl_iql_base

lr: 0.01
logic_lr: 0.01
blender_lr: 0.01
modules:
  - type: nsfr
    rules: default
  - type: cew
    fyd: true
blender_mode: neural
actor_mode: logic
fyd: true
ecm_dthr: 0.1
env:
  rules: default
