name: pyrenees
env_id: pyrenees
offline_only: true
gamma: 0.99
gae_lambda: 0.95
rules: default
reasoner: nsfr
architecture: mlp
reward_type: outcome
# 3 discrete actions: PS (0), WE (1), FWE (2)
n_actions: 3
