defaults:
  - /agent: blendrl_base
  - _self_

lr: 0.008
logic_lr: 0.008
blender_lr: 0.008
ent_coef: 0.01
blend_ent_coef: 0.001
vf_coef: 0.5
max_grad_norm: 0.5
clip_coef: 0.2
update_epochs: 10
num_minibatches: 4
anneal_lr: true
batch_size: 64
norm_adv: true
clip_vloss: true
blender_mode: logic
blend_function: softmax
actor_mode: hybrid
joint_training: true
pretrained: false
