defaults:
  - /agent/cql/transformer

name: cql_blendrl_cross_attention
algorithm: blendrl_cql
actor_mode: hybrid
blender_mode: neural
blend_function: softmax
architecture: cross_attention

modules:
  - type: nsfr
    rules: ${env.rules}
  - type: neural
