defaults:
  - /agent/cql/dnn

name: cql_blendrl_human_neural
algorithm: blendrl_cql
actor_mode: hybrid
blender_mode: neural
blend_function: softmax

modules:
  - type: nsfr
    rules: ${env.rules}
  - type: neural
