name: blendrl
algorithm: blendrl
lr: 2.5e-4
logic_lr: 2.5e-4
blender_lr: 2.5e-4
ent_coef: 0.01
blend_ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
clip_coef: 0.1
update_epochs: 4
num_minibatches: 4
anneal_lr: true
batch_size: 64
norm_adv: true
clip_vloss: true
blender_mode: logic
blend_function: softmax
actor_mode: hybrid
joint_training: false
pretrained: false
