defaults:
  - /agent: blendrl_iql_base
  - _self_

lr: 0.01
logic_lr: 0.01
blender_lr: 0.01
batch_size: 256
epochs_per_interval: 10
blend_function: softmax
modules:
  - type: neural
  - type: nsfr
    rules: default
  - type: cew
    fyd: true
blender_mode: neural
actor_mode: hybrid
fyd: true
ecm_dthr: 0.1
env:
  rules: default
